export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function LoginLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" data-theme={"dark"}>
            <body>
                {children}
            </body>
        </html>
    )
}
