'use client'
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 iss.gltf --transform
*/
import React, { useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

export default function IssModel(props: any) {
    const { nodes, materials } = useGLTF('/issLogo/iss-transformed.glb') as any;

    useEffect(() => {
        if (materials['Material.003']) {
            materials['Material.003'].color.set('white');
        }
    }, [materials]);

    return (
        <group {...props} rotation={[0, Math.PI, 0]}>
            <mesh
                geometry={nodes.Plane.geometry}
                material={materials['Material.003']}
                position={[0.31, -2.5, 0]}
                scale={[0.14, 1, 0.14]}
            />
            <mesh
                geometry={nodes.Plane001.geometry}
                material={materials['Material.003']}
                position={[-0.31, 2.5, 0]}
                rotation={[0, 0, Math.PI]}
                scale={[0.14, 1, 0.14]}
            />
            <mesh
                geometry={nodes.Plane002.geometry}
                material={materials['Material.003']}
                position={[0.71, -2.5, 0]}
                scale={[0.06, 1, 0.14]}
            />
            <mesh
                geometry={nodes.Plane003.geometry}
                material={materials['Material.003']}
                position={[-0.21, 0.73, 0]}
                scale={[0.06, 1, 0.14]}
            />
        </group>
    );
}

// Preload model for faster first render
useGLTF.preload('/issLogo/iss-transformed.glb');
